name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --config Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NapCatBoot05
        path: build/Release/*
